name: my test workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs_on: ubuntu-latest
  steps: 
    - uses: actions/checkout@v2
    - name: hello test workflow
    run: echo "hello sourav"
    shell: bash 